[package]
name = "mock-syn-common"
version = "0.1.4"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full", "extra-traits"] }

[features]
test = ["proc-macro2/span-locations"]
